### ISSUE TITLE
zelt --config does not work

### ISSUE THREAD

**Issue by Olamyy** [zalando-incubator/zelt#27]
**Describe the bug**
The documentation mentions zelt can be started with a config file by invoking `zelt --config [config.yaml]`. However, when I do this, nothing happens. I just get the help message. 

**Zelt version**
Output of the command `zelt --version`.
1.2.15

**To Reproduce**
Steps and input files to reproduce the behavior:
1. Create a config file
2. Run `zelt --config [path to your config]`
3. See error

**Expected behavior**
The load test should start with the parameters in the config file

**Screenshots**
```yaml
locustfile: locust-scripts/locustfile.py
manifests: manifests/distributed
worker-pods: 5
```
![image](https://user-images.githubusercontent.com/14059714/85102219-76257100-b204-11ea-96d4-052a0930fe92.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Fedora, MacOS]: MacOS. Issue persists on docker
 - Version: [e.g. 22]

**Additional context**
